import {
  FiBook,
  FiFileText,
  FiPackage,
  FiCalendar,
  FiMapPin,
  FiShield,
  FiUsers,
  FiFlag,
  FiClock,
  FiFolder,
  FiBox,
  FiEdit,
  FiMap,
  FiArchive,
  FiImage,
  FiStar,
  FiBookmark,
  FiGlobe,
  FiHome,
  FiList,
  FiSettings,
  FiSearch,
  FiCheckCircle,
  FiXCircle,
  FiPlus,
  FiMinus,
  FiChevronDown,
  FiChevronUp,
  FiChevronLeft,
  FiChevronRight,
  FiTrash,
  FiUser,
  FiUsers as FiUsersAlt,
  FiBookOpen,
  FiMenu,
} from 'react-icons/fi';

export const ICON_MAP: Record<string, React.ComponentType> = {
  book: FiBook,
  'file-text': FiFileText,
  package: FiPackage,
  calendar: FiCalendar,
  'map-pin': FiMapPin,
  shield: FiShield,
  users: FiUsers,
  flag: FiFlag,
  clock: FiClock,
  'book-open': FiBookOpen,
  folder: FiFolder,
  box: FiBox,
  edit: FiEdit,
  map: FiMap,
  archive: FiArchive,
  image: FiImage,
  star: FiStar,
  bookmark: FiBookmark,
  globe: FiGlobe,
  home: FiHome,
  list: FiList,
  settings: FiSettings,
  search: FiSearch,
  check: FiCheckCircle,
  x: FiXCircle,
  plus: FiPlus,
  minus: FiMinus,
  chevronDown: FiChevronDown,
  chevronUp: FiChevronUp,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  trash: FiTrash,
  user: FiUser,
  usersAlt: FiUsersAlt,
  fallback: FiFolder,
  menu: FiMenu,
};

// For icon picker UI
export const ICON_OPTIONS = [
  { key: 'book', label: 'Book', icon: FiBook },
  { key: 'file-text', label: 'File Text', icon: FiFileText },
  { key: 'package', label: 'Package', icon: FiPackage },
  { key: 'calendar', label: 'Calendar', icon: FiCalendar },
  { key: 'map-pin', label: 'Map Pin', icon: FiMapPin },
  { key: 'shield', label: 'Shield', icon: FiShield },
  { key: 'users', label: 'Users', icon: FiUsers },
  { key: 'flag', label: 'Flag', icon: FiFlag },
  { key: 'clock', label: 'Clock', icon: FiClock },
  { key: 'book-open', label: 'Book Open', icon: FiBookOpen },
  { key: 'folder', label: 'Folder', icon: FiFolder },
  { key: 'box', label: 'Box', icon: FiBox },
  { key: 'edit', label: 'Edit', icon: FiEdit },
  { key: 'map', label: 'Map', icon: FiMap },
  { key: 'archive', label: 'Archive', icon: FiArchive },
  { key: 'image', label: 'Image', icon: FiImage },
  { key: 'star', label: 'Star', icon: FiStar },
  { key: 'bookmark', label: 'Bookmark', icon: FiBookmark },
  { key: 'globe', label: 'Globe', icon: FiGlobe },
  { key: 'home', label: 'Home', icon: FiHome },
  { key: 'list', label: 'List', icon: FiList },
  { key: 'settings', label: 'Settings', icon: FiSettings },
  { key: 'search', label: 'Search', icon: FiSearch },
  { key: 'check', label: 'Check', icon: FiCheckCircle },
  { key: 'x', label: 'X', icon: FiXCircle },
  { key: 'plus', label: 'Plus', icon: FiPlus },
  { key: 'minus', label: 'Minus', icon: FiMinus },
  { key: 'chevronDown', label: 'Chevron Down', icon: FiChevronDown },
  { key: 'chevronUp', label: 'Chevron Up', icon: FiChevronUp },
  { key: 'chevronLeft', label: 'Chevron Left', icon: FiChevronLeft },
  { key: 'chevronRight', label: 'Chevron Right', icon: FiChevronRight },
  { key: 'trash', label: 'Trash', icon: FiTrash },
  { key: 'user', label: 'User', icon: FiUser },
  { key: 'usersAlt', label: 'Users Alt', icon: FiUsersAlt },
  { key: 'menu', label: 'Menu', icon: FiMenu },
]; 